---
title: Voeg een achtergrondafbeelding toe
hero_image: images/banner.png
description: Voeg een achtergrondafbeelding toe aan een webpagina.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Voeg een achtergrondafbeelding toe
