---
title: Ajouter une image d'arrière-plan
hero_image: images/banner.png
description: Ajoute une image d'arrière-plan à une page web.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Ajouter une image d'arrière-plan
